[theme]
base = "light"
backgroundColor = "#F4F4F0"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B1E21"
primaryColor = "#22385C"
font = "sans serif"

[server]
enableStaticServing = true
headless = true

[browser]
gatherUsageStats = false
